// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ParseRequest struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParseRequest) Reset()         { *m = ParseRequest{} }
func (m *ParseRequest) String() string { return proto.CompactTextString(m) }
func (*ParseRequest) ProtoMessage()    {}
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *ParseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParseRequest.Unmarshal(m, b)
}
func (m *ParseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParseRequest.Marshal(b, m, deterministic)
}
func (m *ParseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParseRequest.Merge(m, src)
}
func (m *ParseRequest) XXX_Size() int {
	return xxx_messageInfo_ParseRequest.Size(m)
}
func (m *ParseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ParseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ParseRequest proto.InternalMessageInfo

func (m *ParseRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type ParsedURLResponse struct {
	Icon                 string   `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Images               []string `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ParsedURLResponse) Reset()         { *m = ParsedURLResponse{} }
func (m *ParsedURLResponse) String() string { return proto.CompactTextString(m) }
func (*ParsedURLResponse) ProtoMessage()    {}
func (*ParsedURLResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *ParsedURLResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ParsedURLResponse.Unmarshal(m, b)
}
func (m *ParsedURLResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ParsedURLResponse.Marshal(b, m, deterministic)
}
func (m *ParsedURLResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParsedURLResponse.Merge(m, src)
}
func (m *ParsedURLResponse) XXX_Size() int {
	return xxx_messageInfo_ParsedURLResponse.Size(m)
}
func (m *ParsedURLResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ParsedURLResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ParsedURLResponse proto.InternalMessageInfo

func (m *ParsedURLResponse) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *ParsedURLResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ParsedURLResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ParsedURLResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ParsedURLResponse) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func init() {
	proto.RegisterType((*ParseRequest)(nil), "api.ParseRequest")
	proto.RegisterType((*ParsedURLResponse)(nil), "api.ParsedURLResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 203 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x09, 0x4e, 0x2b, 0x72, 0x30, 0xd0, 0x13, 0xaa, 0x2c, 0x26, 0x2b, 0x53, 0xa7, 0x0e,
	0x30, 0x30, 0xf2, 0x02, 0x1d, 0x2a, 0x4b, 0x7d, 0x00, 0x93, 0x9c, 0xa2, 0x93, 0x12, 0xdb, 0xd8,
	0xce, 0x53, 0xf0, 0xd2, 0xc8, 0x4e, 0xa4, 0x66, 0xfb, 0xef, 0xbb, 0x7f, 0xf8, 0x3f, 0x68, 0x8c,
	0xe7, 0xb3, 0x0f, 0x2e, 0x39, 0x14, 0xc6, 0x73, 0xab, 0xe0, 0xe5, 0x6a, 0x42, 0x24, 0x4d, 0xbf,
	0x33, 0xc5, 0x84, 0xaf, 0x20, 0xe6, 0x30, 0xca, 0x4a, 0x55, 0xa7, 0x46, 0xe7, 0xd8, 0xfe, 0x55,
	0x70, 0x28, 0x95, 0xfe, 0xa6, 0x2f, 0x9a, 0xa2, 0x77, 0x36, 0x12, 0x22, 0xd4, 0xdc, 0x39, 0xbb,
	0x16, 0x4b, 0xce, 0xcc, 0x9a, 0x89, 0xe4, 0xe3, 0xc2, 0x72, 0xc6, 0x37, 0xd8, 0x25, 0x4e, 0x23,
	0x49, 0x51, 0xe0, 0x72, 0xa0, 0x82, 0xe7, 0x9e, 0x62, 0x17, 0xd8, 0x27, 0x76, 0x56, 0xd6, 0xe5,
	0xb7, 0x45, 0x78, 0x84, 0x3d, 0x4f, 0x66, 0xa0, 0x28, 0x77, 0x4a, 0x9c, 0x1a, 0xbd, 0x5e, 0x1f,
	0xdf, 0x50, 0x5f, 0xd9, 0x0e, 0xf8, 0x05, 0x4f, 0x65, 0xd4, 0x4d, 0x5f, 0xf0, 0x70, 0xce, 0x52,
	0x5b, 0x8d, 0xf7, 0xe3, 0x1d, 0x6d, 0x67, 0xb7, 0x0f, 0x3f, 0xfb, 0x22, 0xff, 0xf9, 0x1f, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0xb3, 0xc0, 0x97, 0x09, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PingClient is the client API for Ping service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PingClient interface {
	ParseURL(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParsedURLResponse, error)
}

type pingClient struct {
	cc *grpc.ClientConn
}

func NewPingClient(cc *grpc.ClientConn) PingClient {
	return &pingClient{cc}
}

func (c *pingClient) ParseURL(ctx context.Context, in *ParseRequest, opts ...grpc.CallOption) (*ParsedURLResponse, error) {
	out := new(ParsedURLResponse)
	err := c.cc.Invoke(ctx, "/api.Ping/ParseURL", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PingServer is the server API for Ping service.
type PingServer interface {
	ParseURL(context.Context, *ParseRequest) (*ParsedURLResponse, error)
}

func RegisterPingServer(s *grpc.Server, srv PingServer) {
	s.RegisterService(&_Ping_serviceDesc, srv)
}

func _Ping_ParseURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PingServer).ParseURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Ping/ParseURL",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PingServer).ParseURL(ctx, req.(*ParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ping_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Ping",
	HandlerType: (*PingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ParseURL",
			Handler:    _Ping_ParseURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
